JAVASCRIPT/Leccion01/01-01-EjerciciosJSPrimerSemana.js
JAVASCRIPT/Leccion01/index.html

Ejercicio de javaScript ciclo while

Commit ejercicio de ciclos While JS

---

JAVASCRIPT/Leccion01/01-01-EjerciciosJSPrimerSemana.js
JAVASCRIPT/Leccion01/index.html

Mostrar el cuadrado de un numero hasta que se digite un valor negativo.

Ejercicio While Ivan Matias

---

JAVA/Leccion01/MundoPC/MundoPC/src/ar/com/system2023/mundopc/Orden.java

solicito revisión e integración del código.

se agrego la clase Orden

---

JAVASCRIPT/TSLeccion02/02-03-arreglos.js

se solicita revisión e integración

Se agregó: Preguntar si es un arreglo

---

PYTHON/Archivos/Leccion02/manejo_archivos.py

Ejercicio Realizado Por Juan Carlos Gutierrez

RecorrerArreglo#44

---

PYTHON/Archivos/Leccion02/manejo_archivos.py

Reverts CodeSystem2022/chacoDevsTeam-3Semestre#54

Revert "RecorrerArreglo#44"

---

PYTHON/Archivos/Leccion02/manejo_archivos.py

Reverts CodeSystem2022/chacoDevsTeam-3Semestre#55

Revert "Revert "RecorrerArreglo#44""

---

PYTHON/Archivos/Leccion02/manejo_archivos.py

Se revierten las ramas mal comiteadas sobre main

Reverse de rama main

---

PYTHON/Archivos/Leccion02/ManejoArchivos.py

Clase Constructora Finalizada - Alejo Gutierrez

PYTHON-Clase Constructora de Manejo de Archivo#41

---

JAVASCRIPT/TSLeccion02/02-03-arreglos.js

Ejercicio de Arreglos - Juan Carlos Gutierrez

JAVASCRIPT-Recorrer los elementos de un Arreglo#44

---

PYTHON/Archivos/Leccion02/archivos_con_with.py

Finalizado el ticket #42 Archivos con with

Archivos con With

---

JAVASCRIPT/TSLeccion03/01-03-funciones.js

Se crea la funcion y se utiliza la palabra reservada return

Funciones.js

---

PYTHON/Leccion03/catalogo_peliculas/test_catalogo_peliculas.py

Test Catalogo Peliculas#80

---

JAVASCRIPT/TSLeccion03/01-03-funciones.js

Test de JAVASCRIPT-Funciones de tipo self y invoking#70, JAVASCRIPT-Funciones del tipo expresión#71

Test ticket #70 #71

---

PYTHON/Leccion03/catalogo_peliculas/servicio/catalogo_peliculas.py

se solicita revision e integracion

Se agregó la clase Catalogo_Pelicula

---

JAVASCRIPT/TSLeccion03/01-03-funciones.js

JAVASCRIPT-Paso por referencia#77

---

JAVASCRIPT/TSLeccion03/01-03-funciones.js

Ingreso Cambios en Tipos de Datos

Funciones-Tipos de Datos. chacoDevsTeam-3Semestre#72

---

JAVA/Leccion02/ArgumentosVariables/src/test/Continentes.java

Se crea la clase Continentes y también el metodo get

Clase Continente

---

JAVA/Leccion02/Enumeraciones/src/test/TestEnumeraciones.java

TestEnumeraciones#94

---

JAVASCRIPT/TSLeccion04/01-04.Objetos.js

Se  desarrolla un objeto, se establece atributos y se muestra en consola el valor de los mismos.Luego se crea  método para concatenar el atributo nombre y apellido.

Se crea Objeto

---

JAVASCRIPT/TSLeccion04/01-04.Objetos.js

Listo para revisión e integración

Agregado como acceder a propiedades #115

---

JAVASCRIPT/TSLeccion04/01-04.Objetos.js

Finalizado el desarrollo del programa

JAVASCRIPT-Agregar y eliminar propiedades de Objeto#116

---

JAVASCRIPT/TSLeccion04/01-04.Objetos.js
JAVASCRIPT/TSLeccion04/index.html

Test JS TICKET#117

---

JAVA/Leccion03/ModificadoresAcceso/src/paquete1/TestDefault.java
JAVA/Leccion03/ModificadoresAcceso/src/paquete2/Clase4.java

Se requiere crear una clase que contenga método, atributo, constructor del tipo private(Video 10)

test JAVA ticket #128

---

JAVA/Leccion04/Sobreescritura/src/domain/Empleado.java

Se requiere crear una clase padre con sus atributos,su constructor y metodo(Video 1)

Test JAVA ticket #139

---

JAVA/Leccion04/Sobreescritura/src/test/TestSobreescritura.java

JAVA-Definir variables para clase Test#141

---

JAVA/Leccion04/Sobreescritura/src/test/TestSobreescritura.java

se solicita revisión e integración.

Clase Test Modificada

---

JAVA/Leccion04/InstanceOf/src/domain/Gerente.java
JAVA/Leccion04/InstanceOf/src/test/TestInstanceOf.java

Se agregó metodo set & get y se modificó el metodo "determinarTipo".

Clase Empleado#144

---

JAVA/Leccion04/InstanceOf/src/test/TestInstanceOf.java

JAVA-Modificar variables en el nuevo proyecto#147

---

PYTHON/Leccion04/BD/delete_registro.py

Se solicita revisión e integración.

Agregado: Eliminar un registro

---

JAVASCRIPT/TSLeccion04/01-04.Objetos.js

Se muestran las diferentes formas de crear un objeto

Ticket#174

---

JAVASCRIPT/TSLeccion04/01-04.Objetos.js

JS-METODOS GET & SET#171

---

PYTHON/Leccion04/BD/v_registros.py

Creacion de registros #166

---

JAVASCRIPT/TSLeccion04/01-04.Objetos.js

Se requiere agregar la propiedad prototype y mostrar los ejemplos (Video 6)

test TICKET #175

---

PYTHON/Leccion04/BD/i_registros.py

PYTHON-INSERT DE UN REGISTRO#167

---

JAVA/Leccion05/ConversionObjetos/src/domain/Escritor.java
JAVA/Leccion05/ConversionObjetos/src/test/TestConversionObjetos.java

JAVA-PRUEBAS DE DOWNCASTING Y UPCASTING#191

---

JAVASCRIPT/TSLeccion04/01-04.Objetos.js

JS-AGREGAR METODOS AL CONSTRUCTOR DEL OBJETO#173

---

JAVA/Leccion05/ClasesAbstractas/src/domain/Rectangulo.java
JAVA/Leccion05/ClasesAbstractas/src/test/testAbstractas.java

Se solicita revisión del código.

Se añadio la clase abstracta #2

---

PYTHON/Leccion04/BD/delete_varios_registros.py
PYTHON/Leccion04/BD/i_v_registros.py

Se creo la clase delete_varios_registros y la clase i_v_registros.

TICKET #210 y TICKET #211

---

PYTHON/Leccion04/BD/transacciones.py

Se creo la clase y se agrego el metodo sin with.

Transacciones#213

---

JAVASCRIPT/TSLeccion05/05-03-clases.js

Se requiere crear geter and seter del atributo apellido, usar console.log para visualizar su estado y aplicar el concepto a clases (Tarea - VIDEO 5 y 6)

test TICKET #218

---

JAVASCRIPT/TSLeccion05/05-03-clases.js

JAVASCRIPT - METODO GET Y SET#217

---

PYTHON/Leccion04/BD/transsacciones_tres.py

Se crea archivo con transacciones 3

Transacciones_3

---

JAVASCRIPT/TSLeccion05/05-03-clases.js

HERENCIA - se requiere crear un metodo en la clase padre y utilizarlo en la clase hija (video 1)

Test TICKET JS#241

---

PYTHON/Leccion07/capa_datos_persona/logger_base.py

Se creo la "Leccion07" con su carpeta "capa_datos_persona" con su correspondiente clase "logger_base.py"

PYTHON - Manejo de logging P1

---

JAVASCRIPT/TSLeccion05/05-03-clases.js
JAVASCRIPT/TSLeccion05/index.html

JAVASCRIPT - Sobreescritura de metodos

Ticket#242

---

JAVA/Leccion06/Interfaces/src/accesodatos/IAccesoDatos.java

JAVA - Manejo de Interfaces - parte 1

chacoDevsTeam-3Semestre#247

---

PYTHON/Leccion04/BD/.idea/.gitignore
PYTHON/Leccion04/BD/.idea/BD.iml
PYTHON/Leccion04/BD/.idea/inspectionProfiles/profiles_settings.xml
PYTHON/Leccion04/BD/.idea/misc.xml
PYTHON/Leccion04/BD/.idea/modules.xml
PYTHON/Leccion04/BD/.idea/vcs.xml
PYTHON/TrabajoFinal3Semestre/.idea/.gitignore
PYTHON/TrabajoFinal3Semestre/.idea/TrabajoFinal3Semestre.iml
PYTHON/TrabajoFinal3Semestre/.idea/inspectionProfiles/profiles_settings.xml
PYTHON/TrabajoFinal3Semestre/.idea/misc.xml
PYTHON/TrabajoFinal3Semestre/.idea/modules.xml
PYTHON/TrabajoFinal3Semestre/.idea/vcs.xml
PYTHON/TrabajoFinal3Semestre/GestionBiblioteca/config/logger_base.py

Se requiere crear una clase llamada logger_base la cual se configurara nuestros logs a nivel de INFO

Test ticket Proyecto Final #254

---

JAVA/Leccion06/Interfaces/src/accesodatos/ImplementacionOracle.java

JAVA - Manejo de Interfaces - parte 3#249

---

PYTHON/Leccion07/capa_datos_persona/logger_base.py

PYTHON - Manejo de logging: parte 2 #240

---

JAVA/Leccion06/Interfaces/src/accesodatos/ImplementacionMySql.java

JAVA - Manejo de Interfaces - parte 2#248

---

JAVASCRIPT/TSLeccion05/05-03-clases.js

Se solicita revisión del código a integrarse.

Se agrego el atributo contador estatico

---

PYTHON/Leccion07/capa_datos_persona/conexion.py

PYTHON-Creación de la Clase Conexion (Parte2)#270

---

PYTHON/TrabajoFinal3Semestre/GestionBiblioteca/UI/ui.py

Se creo el paquete ui y dentro la clase ui.py en el cual se modificó el diseño para la ejecución por consola.

PYTHON 2 ETAPA-Capa UI-ui.py

---

JAVASCRIPT/TSLeccion05/05-03-clases.js

JAVASCRIPT-Atributos estáticos vs No estáticos#274

---

JAVA/Leccion07/JavaBeans/src/domain/Persona.java
JAVA/Leccion07/JavaBeans/src/javabeans/JavaBeans.java

Ticket#282

---

JAVA/Leccion08/ManejoExcepciones1/src/test/TestExcepciones.java

(clase 8, video 4Pt2): Se requiere trabajar con Try (clase 8, video 5 Pt3, explicacion de los diagramas NO HACE CODIGO) (clase 8, video 6 Pt4): Solo se requiere comentar el código.

Test JAVA ticket #285

---

JAVASCRIPT/TSLeccion05/05-03-clases.js

Se ha creado correctamente las constantes estaticas

Ticket#276

---

PYTHON/Leccion07/capa_datos_persona/persona_dao.py

PYTHON-creación de la Clase PersonaDAO

Ticket#271

---

JAVASCRIPT/TSLeccion07/Persona.js

se solicita revisión e integración del código.

Se creó el directorio TSLeccion07 y se agregó la clase Persona

---

PYTHON/TrabajoFinal3Semestre/GestionBiblioteca/core/core_autor.py

se solicita integración del código

Se agrego la clase core_autor al paquete core

---

JAVASCRIPT/TSLeccion07/Cliente.js

JAVASCRIPT-Creación de la Clase Cliente

Ticket#314

---

PYTHON/Leccion07/capa_datos_persona/persona_dao.py

Ticket#310

---

JAVA/Leccion09/CalculadoraUTN/src/CalculadoraUTN.java

Se realiza el menu de la calculadora

Ticket#324

---

JAVA/Leccion09/CalculadoraUTN/src/CalculadoraUTN.java

JAVA-Agregamos el switch en el MENU#323

---

JAVASCRIPT/TSLeccion07/Empleado.js

Chaco devs team 3 semestre#315

---

JAVA/Leccion09/CalculadoraUTN/src/CalculadoraUTN.java

JAVA-Ciclo y su salida con break

Ticket#325

---

PYTHON/TrabajoFinal3Semestre/GestionBiblioteca/domain/libro.py

ProyectoFinal#228

---

PYTHON/Leccion07/capa_datos_persona/persona_dao.py

Se requiere desarrollar en la clase persona_dao.py el metodo actualizar el cual debe realizar una transaccion a la tabla_bd este debe actualizar un registro ya guardado mediante un id_persona se debe realizar la prueba correspondiente (video 4)

test TICKET PYTHON #311

---

JAVA/Leccion09/CalculadoraUTN/src/CalculadoraUTN.java

Se requiere crear una funcion donde migremos el menu principal y utilizemos esta funcion. (BLOQUEADO HASTA TERMINAR TICKET 326) (video 8)

Test ticket JAVA #327

---

JAVASCRIPT/PruebaPersonas.js

JAVASCRIPT-Creación de la Clase PruebaPersona#316

---

JAVASCRIPT/PruebaPersonas.js

Se añadieron las pruebas correspondientes y se hicieron unas correcciones en el codigo.

JAVASCRIPT-Prueba Clase Empleado y Cliente

---

PYTHON/TrabajoFinal3Semestre/GestionBiblioteca/core/core_socio.py

PYTHON 1 ETAPA-Capa Core-core_socio.py

Ticket#258

---

PYTHON/TrabajoFinal3Semestre/GestionBiblioteca/core/core_solicitud.py

PYTHON 1 ETAPA-Capa Core-core_solicitud.py#261

---

PYTHON/TrabajoFinal3Semestre/GestionBiblioteca/UML/Enum/estados_libro.py

PYTHON 1 ETAPA-Paquete enum-Enum estado_libro.py#230

---

PYTHON/Leccion07/capa_datos_persona/conexion.py
PYTHON/Leccion07/capa_datos_persona/persona_dao.py

se requiere desarrollar el metodo obtenerConexion se debe obtener la conexion desde el pool (video 4), fix en clase persona_dao

test TICKET PYTHON #358

---

PYTHON/TrabajoFinal3Semestre/GestionBiblioteca/service/service_libro.py

Se requiere crear el service de libro el cual contrendra varias opciones a elegir por el usuario: 1).Nuevo libro: solicitara el ingreso de los datos de libro a guardar en BD, se solicitara el ingreso del ISBN se validara que no exista uno en BD, en caso de que exista se informara al usuario que debe realizar el proceso de actualizacion de cantidad, en caso contrario se proseguira con la solicitudde ingreso de datos, para el campo autor y socio se preguntara al usuario de que manera registrara asi se validara de que primero se hayan cargado en sus correspondientes tablas. 2).Listado de libros: se realizara una consulta a la BD para traer todos los registros. 3).Baja libro: Mediante el ID ingresado por el usuario se dara de baja un libro. 4).Modificar datos de libro: Mediante un ID de libro …

Test TICKET proy. final PYTHON #352

---

PYTHON/Leccion07/capa_datos_persona/conexion.py

PYTHON- Pruebas creando objetos del Pool de conexiones

Ticket #359

---

JAVASCRIPT/TSLeccion08/SistemasVentas.js

Se creo la clase Producto con sus respectivos atributos.

JAVASCRIPT- Clase Producto

---

JAVASCRIPT/TSLeccion08/SistemasVentas.js

Se agregaron los métodos faltantes

Corrección en la clase Orden

---

JAVA/Leccion11/ListarPersonas/src/ListadoPersonasApp.java
JAVA/Leccion11/ListarPersonas/src/Main.java

JAVA- Creamos el Menu#370

---

JAVA/Leccion11/Leccion11.iml
JAVA/Leccion11/ListarPersonas/src/ListadoPersonasApp.java

Chaco devs team 3 semestre#371

---

PYTHON/TrabajoFinal3Semestre/GestionBiblioteca/service/service_socio.py

PYTHON 2 ETAPA-Capa Service-service_socio.py

Ticket#353

---

PYTHON/TrabajoFinal3Semestre/GestionBiblioteca/service/solicitud_service.py

Se crea la clase solicitud_service

Clase solicitud

---

PYTHON/TrabajoFinal3Semestre/GestionBiblioteca/service/service_libro.py

Se requiere mejorar el siguiente mensaje que se muestra en el service solicitud LIBRO
Debe ingresar un modo de registro
1: Titulo:
2: ISBN:
3: id:
metodo: service_solicitud_alta
Clase service_solicitud linea: 19

Test Correccion de mensaje LIBRO en Service Solicitud

---

PYTHON/TrabajoFinal3Semestre/GestionBiblioteca/service/service_solicitud.py

Se arregló el menú de presentacion en ejecución.

PYTHON 2 ETAPA - Correccion de mensaje LIBRO en Service Solicitud

---

JAVA/Leccion12/SistemaEstudiantes/.gitignore
JAVA/Leccion12/SistemaEstudiantes/.idea/.gitignore
JAVA/Leccion12/SistemaEstudiantes/.idea/encodings.xml
JAVA/Leccion12/SistemaEstudiantes/.idea/misc.xml
JAVA/Leccion12/SistemaEstudiantes/.idea/vcs.xml
JAVA/Leccion12/SistemaEstudiantes/pom.xml
JAVA/Leccion12/SistemaEstudiantes/src/main/java/UTN/Main.java

(Sinconizar con Maven y Agregar dependencia -Crear una aplicacion de Sistema Estudiantes - Desde IntelliJ (Video 4) )

Test ticket JAVA #389

---

JAVA/Leccion12/SistemaEstudiantes/src/main/java/UTN/conexion/Conexion.java

ticket#391

---

JAVA/Leccion12/SistemaEstudiantes/src/main/java/UTN/Main.java
JAVA/Leccion12/SistemaEstudiantes/src/main/java/UTN/conexion/Conexion.java

Se arreglaron los errores que no permitian el correcto funcionamiento del codigo.

JAVA - Conexion PT 2

---

JAVA/Leccion12/.idea/.gitignore
JAVA/Leccion12/.idea/Leccion12.iml
JAVA/Leccion12/.idea/misc.xml
JAVA/Leccion12/.idea/modules.xml
JAVA/Leccion12/.idea/vcs.xml
JAVA/Leccion12/SistemaEstudiantes/pom.xml

desarrollo finalizado chacoDevsTeam-3Semestre #390

JAVA - Maven y Dependencia PT 2#390

---

PYTHON/TrabajoFinal3Semestre/GestionBiblioteca/ui/ui.py

Se agregaron un par de arreglos a la clase UI.

Correciones UI

---

JAVA/Leccion12/SistemaEstudiantes/src/main/java/UTN/dominio/Estudiante.java

Crear la clase estudiante(Video 1).Crear la clase estudiante y cada uno de sus atributos.Y agregar diferentes constructores

Test Ticket JAVA #419

---

JAVA/Leccion12/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java

Se creo la clase EstudianteDAO y también los objetos de tipo conexion.

Java-Clase DAO

---

JAVA/Leccion12/SistemaEstudiantes/src/main/java/UTN/conexion/Conexion.java
JAVA/Leccion12/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java

Java-Listar los estudiantes#422

---

JAVA/Leccion12/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java

Java-Agregar try y catchAux#421

---

JAVA/Leccion12/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java

Pruebas del metodo agregar estudiantes y algunas correcciones

---

JAVA/Leccion12/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java

Java-método modificarEstudiante

Ticket#425

---

JAVA/Leccion12/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java

Reverts CodeSystem2022/chacoDevsTeam-3Semestre#438

Revert "Ticket#425"

---

JAVA/Leccion12/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java

Java-método modificarEstudiante

Ticket#425#1
